config:
  url: 'https://github.com/SchweizerischeBundesbahnen/releasetrain.git'
  baseurl: 'https://github.com/SchweizerischeBundesbahnen/releasetrain/raw/feature/releasetrainconfig'
  branch: feature/releasetrain
  user: marthaler
  password: ***

store
  url: 'https://github.com/SchweizerischeBundesbahnen/releasetrain.git'
  branch: feature/releasetrain-state-do-not-touch
  user: marthaler
  password: ***

jenkins
  url: https://ci.sbb.ch/
  buildtoken: build

http
  user: ***
  password: ***

smtp
  host: ***

logging
  level
    ch: INFO
  pattern
    console: %5p %d{mm:ss} %msg%n
