config:
  url: https://github.com/SchweizerischeBundesbahnen/releasetrain.git
  baseurl: https://github.com/SchweizerischeBundesbahnen/releasetrain/raw/feature/releasetrainconfig
  branch: feature/releasetrain-devl-config
  user: marthaler
  password: xy

store:
  url: d:/releasetrain
  branch: feature/releasetrain-state-do-not-touch
  user: marthaler
  password: xy

jenkins:
  url: https://ci.sbb.ch/
  buildtoken: build

http:
  user: releasetrain
  password: releasetrain11

smtp:
  host: xy

logging:
  level:
    ch: INFO
  pattern:
    console: '%5p %d{mm:ss} %msg%n'

security:
  user:
    name: user
    password: user
    role: USER
  basic:
    enabled: false